### ISSUE TITLE
500 Error when refreshing session token

### ISSUE THREAD

**Issue by lizrea** [ebsco/edsapi-koha-plugin#126]
On 22.05, Debian Buster there seems to be a problem refreshing the session token:

Wed Feb 08 14:32:57.553294 2023] [cgi:error] [pid 84946] [client xxx:44924] AH01215: Can't call method "binip" on an undefined value at /usr/share/perl5/Net/IP.pm line 757.: /var/lib/koha/library/plugins/Koha/Plugin/EDS/opac/eds-raw.pl

**Comment by mmabrahamson** [comment]
Hello!  Happy to help out on this as best I can.  We were also contacted by the site having this issue and I was able to see that the plugin is failing all around on their instance.  Unfortunately I don't have a Debian instance on which to run tests presently, and our existing Ubuntu instance is working as expected, so I may need some help troubleshooting this.  

Can you help me with a few clarifying items so I can better test locally?

Which version of Koha are you on?  Our test instance is on 22.05.00.000, so I'm happy to update to your version and see if we can duplicate the issue.

When you installed/updated the plugin, which version of the plugin are you using?  We are currently testing against plugin version 21.11003, which should be compatible with 22.05, but again it may be a later version of Koha created an issue.

Did you go into configuration and save the config file after any recent update to the plugin?  Some files require that you go in and save after reuploading the plugin in order to build them out with current data.

Do you have any custom.js files loaded for your install of the plugin?  Sometimes we've seen customizations create unexpected conflicts.

Hopefully with a little more information I can at least verify if we have the same issues on our local Ubuntu install or if it is definitely limited to Debian Buster.

**Comment by mmabrahamson** [comment]
As an additional note, I updated our test site to the latest 22.05, 22.05.09.000, to make sure we weren't causing a more generic issue across all installs.  It's still working as expected on the Ubuntu side.  I'll see about getting a Debian machine created that we can test against as well, if possible.

**Comment by mmabrahamson** [comment]
One more note, I can't see any references to the binip function Net::IP in the core code of the plugin.  Have any local modifications been made that would call this method?

**Comment by lizrea** [comment]
Hi,
This is version 22.05.09 by now, there are no custom js files, and it seems we cannot connect to the API to refresh the configuration. There should not be anything custom in the plugin that I'm aware of - we reinstalled it from here as part of our troubleshooting. The plugin is the same version as yours, 21.11003

The configuration screen says: 

{"DetailedErrorDescription":"Session token is missing.","ErrorDescription":"Session Token Missing","ErrorNumber":"108"}

the binip error appears in our log when we attempt to reup the session.

I hope this helps!
Cheers,
Liz

**Comment by mmabrahamson** [comment]
It sounds like there might be more than one issue at hand here.  Before we test anything else, can we verify the credentials being used to log in?  Let's not do that here, but rather could you email me directly about this piece?  You should be able to respond on the ticket that was attached to this issue.  Best case, if you could screenshot the configuration screen and send it, that would help me out a lot.  Thanks!

**Comment by mmabrahamson** [comment]
Completely understandable!  I've reached out to the customer directly.

**Comment by mmabrahamson** [comment]
Hello!  I'm closing this issue as I was able to resolve it with the customer.  The actual issue was that their configuration was not targeting an eds API profile.  Now that it is, they are reporting it working as expected.
