### ISSUE TITLE
OPACBaseURL prefixed with http:// in admin/configure.tt

### ISSUE THREAD

**Issue by dpavlin** [ebsco/edsapi-koha-plugin#13]
According to Koha systempreferences,  OPACBaseURL ... should be a complete URL, starting with http:// or https://.

However, in `admin/configure.tt` in this plugin, it's prefixed with http:// so retrieving authorization token doesn't work but instead opens new window. (To be honest, it still doesn't work after this change but at least it's a start). It doesn't work because most Koha installations have Intranet installed on different port than OPAC, so using OPACBaseURL to get intranet URL won't work.

Koha version:   3.21.00.037

**Comment by schnydszch** [comment]
It seems I just experienced this when configuring a Koha-EDS integration. However, it's just weird that instead I get http//opacbaseurl//plugin/Koha/Plugin/EDS/opac/eds-raw.pl... The colon is omitted. The intranet uses a different port (8080) and intranet has the same domain name. So in order to make update info work, I instead added :8080 to the URL created by the new window.

**Comment by alvetm** [comment]
Fixed in v16110x+
