### ISSUE TITLE
Plugin broken in 16.11

### ISSUE THREAD

**Issue by WNickC** [ebsco/edsapi-koha-plugin#20]
Remove use of C4:Branches in EDS.pm

Remove use of C4 Branches in eds-search.pl
Replace 
my $branches = Getbranches(); 
with
my $branches = { map { $_->branchcode => $_->unblessed } Koha::Libraries->search };

Remove use of C4::Ratings in eds-search.pl

**Comment by alvetm** [comment]
Many thanks - that worked mostly; I get the following error when trying to get the branches. I'll take a look at what other Koha core files are doing to fix this.

Software error:

Bareword "unblessed" not allowed while "strict subs" in use at /var/lib/koha/library/plugins/Koha/Plugin/EDS/opac/eds-search.pl line 392.
Execution of /var/lib/koha/library/plugins/Koha/Plugin/EDS/opac/eds-search.pl aborted due to compilation errors.

**Comment by WNickC** [comment]
In eds-search.pl:
use Koha::Libraries;

then make that line above:
my $branches = { map { $->branchcode => $->unblessed() } Koha::Libraries->search() };

**Comment by alvetm** [comment]
my $branches = ''; did the job... Able to get the opac record without branch details.

Thanks for raising this.
