### ISSUE TITLE
README.md appears to be incorrect regarding versions

### ISSUE THREAD

**Issue by minusdavid** [ebsco/edsapi-koha-plugin#96]
On the README it says "use branch:Master for 19.11+ (includes latest features and updates)". However, the KPZ provided on master is eds_plugin_20.05002.kpz and it is listed as having a minimum version of 20.05

**Comment by minusdavid** [comment]
I'm going to guess that commit 6de8fa804a1d0f6891036e3cf377cb306363968c is the last one compatible with 19.11?

**Comment by mmabrahamson** [comment]
Actually the current 20.05 should be compatible.  I'm making some changes to how our builder works so that we can better set the minimum version and testing that it is still compatible before releasing.

**Comment by mmabrahamson** [comment]
I was wrong, 20.05 wasn't compatible with 19.11 due to the change in cart downloads.  Leveraging the GitHub Releases as suggested, I've got a separate release for 19.11 that is stable, as well as 19.05 and 20.05.  This should make it easier to find the right version.  I'll be updating the readme as well.  Closing this in the meantime.
