### ISSUE TITLE
Using Github's "Releases" functionality

### ISSUE THREAD

**Issue by minusdavid** [ebsco/edsapi-koha-plugin#97]
Would it be possible to use Github's "Releases" functionality? 

Doing so would make it far easier to find the correct version of the plugin to use for different versions of Koha. If you look at https://github.com/bywatersolutions/dev-koha-plugin-kitchen-sink, you can see the .github/workflows are used to automate this process.

Storing a compiled/compressed file in the Git itself is rare, and the Github "Releases" would be a good place to externalize that.

**Comment by mmabrahamson** [comment]
Great idea!  I'm working on setting up some releases that better track the stable versions.

**Comment by mmabrahamson** [comment]
I've done some initial work to get releases set up.  When we've got a little more time, I'm going to work on automating it and I'll get an update to the readme in master soon.  Thanks for this suggestion!  In the meantime I'm going to close the issue since we've got an implementation of this now and a plan going forward to consider automating it.
